<a href="https://colab.research.google.com/github/lara-ms/Aula-M06/blob/main/ATV_2_Lara_Si%C3%A9cola.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Nome: Lara Moreira Siécola
## Matrícula: 2365

---

# Atividade 2 - Algoritmos e Métodos Numéricos, Erros, Medidas e Fontes

Uma equipe de desenvolvedores e engenheiros está projetando um sistema de monitoramento térmico em tempo real para as CPUs de um Data Center. O objetivo do sistema é acionar o resfriamento de emergência sempre que a temperatura da CPU atingir o limite crítico de segurança, definido como $85\text{ }^\circ\text{C}$ por um sensor óptico padrão de calibração de altíssima precisão.
Para baratear o custo, a equipe testou 6 módulos de sensores de temperatura IoT diferentes (série de nós de sensores $S_1$ a $S_6$). Devido a limitações de hardware — como a resolução do Conversor Analógico-Digital (ADC) do microcontrolador (erro de quantização e truncamento), ruído eletromagnético e tolerância dos componentes —, os valores digitais lidos por cada sensor apresentaram pequenas divergências em relação ao valor real de referência.



Os resultados dos sensores estão na tabela abaixo:

| Módulo de Sensor | Temperatura Lida (°C) |
| --- | --- |
| P1 | 84,820 |
| P2 | 85,150 |
| P3 | 84,985 |
| P4 | 85,040 |
| P5 | 85,310 |
| P6 | 84,910 |


Seu objetivo é analisar esses dados e calcular diferentes métricas de erro, usando as bibliotecas pandas e numpy.

---

In [1]:
from IPython.display import display
# Importando bibliotecas

#Analise de dados
import pandas as pd
import numpy as np

In [2]:
Valor_referencia = 85
#Tabela de dados
tabela = {
    "Sensor": [
        "P1",
        "P2",
        "P3",
        "P4",
        "P5",
        "P6",
    ],
    "Temp_Lida (°C)": [84.820, 85.150, 84.985, 85.040, 85.310, 84.910],
}

dados = pd.DataFrame(tabela)
display(dados)

  Sensor  Temp_Lida (°C)
0     P1          84.820
1     P2          85.150
2     P3          84.985
3     P4          85.040
4     P5          85.310
5     P6          84.910

### Parte 1 - Erro Absoluto, Erro Relativo e Erro Percentual

Calcule o Erro Absoluto, o Erro Relativo e o Erro Percentual dos valores medidos.

In [3]:
# Erro Absoluto
erro_abs = np.abs(Valor_referencia - dados["Temp_Lida (°C)"])
print("Erro Absoluto:")
print(erro_abs)

Erro Absoluto:
0    0.180
1    0.150
2    0.015
3    0.040
4    0.310
5    0.090
Name: Temp_Lida (°C), dtype: float64

In [4]:
# Erro Relativo
erro_rel = erro_abs / Valor_referencia
print("Erro Relativo:")
print(erro_rel)

Erro Relativo:
0    0.002118
1    0.001765
2    0.000176
3    0.000471
4    0.003647
5    0.001059
Name: Temp_Lida (°C), dtype: float64

In [5]:
# Erro Percentual
erro_per = erro_rel * 100
print("Erro Percentual:")
print(erro_per)

Erro Percentual:
0    0.211765
1    0.176471
2    0.017647
3    0.047059
4    0.364706
5    0.105882
Name: Temp_Lida (°C), dtype: float64

**Formulário para cálculo de erros**

- Erro Absoluto:  
$$E_a = |V_t - V_m|$$

- Erro Relativo:  
$$E_r = \frac{E_a}{|V_m|}$$

- Erro Percentual:  
$$E_p = E_r \times 100\%$$

Onde:  
- $V_t$ = valor teórico de referência  
- $V_m$ = valor medido pelo sensor

### Parte 2 - Arredondamento e Truncamento

Um engenheiro biomédico está testando um novo sensor para um oxímetro de pulso hospitalar (aparelho que mede a saturação de oxigênio no sangue, $SpO_2$).

O sensor faz a medição com alta precisão (quatro casas decimais), mas o visor do aparelho só tem espaço para mostrar o número arredondado com duas casas decimais.

As medições feitas pelo sensor em cinco pacientes foram:

| Paciente | Oxigênio Medido (%) |
| --- | --- |
| P1 | 92.3456 |
| P2 | 98.8765 |
| P3 | 95.5555 |
| P4 | 97.4999 |
| P5 | 90.0501 |

### 1 - Fazer um DataFrame para organização visual dos dados

In [6]:
#Tabela de dados
tabela = {
    "Paciente": [
        "P1",
        "P2",
        "P3",
        "P4",
        "P5"
    ],
    "Oxigênio Medido (%)": [92.3456, 98.8765, 95.5555, 	97.4999, 90.0501],
}

dados = pd.DataFrame(tabela)
display(dados)

  Paciente  Oxigênio Medido (%)
0       P1              92.3456
1       P2              98.8765
2       P3              95.5555
3       P4              97.4999
4       P5              90.0501

### 2 - Arredonde todos os valores para 2 casas decimais

In [7]:
dados['Arredondado_2cd'] = dados['Oxigênio Medido (%)'].round(2)
print(dados['Arredondado_2cd'])

0    92.35
1    98.88
2    95.56
3    97.50
4    90.05
Name: Arredondado_2cd, dtype: float64

### 3 - Trunque os valores para 1 casa decimal

In [8]:
dados['Truncado_1cd'] = np.trunc(dados['Oxigênio Medido (%)']*10)/10
print(dados['Truncado_1cd'])

0    92.3
1    98.8
2    95.5
3    97.4
4    90.0
Name: Truncado_1cd, dtype: float64

### 4 - Qual é o valor inteiro mais próximo para cada?

In [9]:
dados['Inteiro_proximo'] = dados['Oxigênio Medido (%)'].round(0).astype(int)
print(dados['Inteiro_proximo'])

0    92
1    99
2    96
3    97
4    90
Name: Inteiro_proximo, dtype: int64

### 5 - Mostre os resultados dentro de uma tabela

In [10]:
dados

,Paciente,Oxigênio Medido (%),Arredondado_2cd,Truncado_1cd,Inteiro_proximo
0,P1,92.3456,92.35,92.3,92
1,P2,98.8765,98.88,98.8,99
2,P3,95.5555,95.56,95.5,96
3,P4,97.4999,97.50,97.4,97
4,P5,90.0501,90.05,90.0,90




<span style="font-size:90%">

**Guia Rápido: Arredondamento e Truncamento**

- Arredondar para n casas decimais: `dados["Comprimento Medido (cm)"].round(0)`  
- Truncar para n casas decimais: `np.trunc(dados["Comprimento Medido (cm)"] * 10) / 10`  
- Arredondar para inteiro mais próximo: `dados["Comprimento Medido (cm)"].round(0).astype(int)`

</span>

## Parte Teórica

**Questão 1.**

Julgue as afirmativas abaixo como V (Verdadeiro) ou F (Falso) e justifique as que forem Falsas.

1. O erro absoluto nos dá a exata noção do impacto da falha, independentemente da ordem de grandeza do valor medido.

2. O instrumento de medida escolhido para medir uma grandeza deve ser coerente com aquilo que se deseja medir.

3. O erro percentual é calculated multiplicando o erro absoluto por 100%.

4. Erros aleatórios não podem ser eliminados por calibração de instrumentos, mas podem ser minimizados através de repetições e métodos estatísticos (como a média).

5. O número de algoritmos significativos de uma grandeza é determinado pela sua incerteza.

**Resposta:**

1. **Falsa**. O erro absoluto nos indica a magnitude da diferença entre o valor medido e o valor real, sem considerar a escala. O erro relativo nos faz entender o real impacto.

2. **Verdadeiro**.

3. **Falsa**. O erro percentual é o erro relativo multiplicado por 100%.

4. **Verdadeiro**.

5. **Verdadeiro**.

**Questão 2.**

Quando você faz a medição de alguma grandeza, com um instrumento de medição qualquer, em qual conjunto cai a medida que você
obteve?

Conjunto dos números Naturais, Inteiros, Racionais, Irracionais, Reais ou Complexos? Justifique sua resposta

**Resposta:**

A medida que foi possível se obter é do conjunto dos números Racionais, por conta de limitação na precisão e resolução(escala). O número tem um número finito de casas decimais.